---
- assert: { that: report_file is defined }

- include: scan.yml
  vars:
    group: "{{ target.group }}"
    port: "{{ target.port }}"
    proto: "{{ target.proto | default('tcp') }}"
    test_from: "{{ target.test_from }}"
  with_list: "{{ firewall_rules }}"
  loop_control:
    loop_var: target

- name: Create report directory
  file:
    path: "{{ report_file | dirname }}"
    state: directory

- debug: var=port_scan_result verbosity=2

- name: Generate report
  template:
    src: port_report.j2
    dest: "{{ report_file }}"
